### PR TITLE
Bug/ux 188 total status columns order history

### LINKED ISSUE #188: Fix "Total" column and "Status" columns in Order History table
For each Order:
Total is currently all $0.00.
Status is currently blank.
screen shot 2015-02-19 at 11 51 42 am

### PR DESCRIPTION
**Pull request by gnklausner**
Closes #188

### CODE REVIEW

File: assets/js/app/users/orders/user_orders_controller.js [hunk 1]
```diff
@@ -1,19 +1,52 @@
...
 };
 
-UserOrderController.resolve = {
-    /**@ngInject*/
-    orders: function(UserOrders, currentUser) {
-        return UserOrders.query({staff_id: currentUser.id}).$promise;
+UserOrderController.prototype.getOrderStatus = function(orders) {
+  _.each(orders, function(order)
+  {
+    if (_.every(order.order_items, function(order_item){return order_item.provision_status === "retired";})) {
```
Comment (stackus) [inline assets/js/app/users/orders/user_orders_controller.js]: Using either the `_matches()` or `_.matchesProperty()` shorthands for `_.every()` will make this line easier to read.

The `_matches()` shorthand for example.
```
if (_.every(order.order_items, {provision_status: 'retired'})) {
```

Comment (gnklausner) [inline assets/js/app/users/orders/user_orders_controller.js]: Do you not have to explicitly use ```_.isMatch()```? As well, do you know if there is a way I can test that this if-statement will be fired correctly?

Comment (stackus) [inline assets/js/app/users/orders/user_orders_controller.js]: You don't. In fact lodash supports shorthand usages for quite a few of its methods.

https://lodash.com/docs#every

I don't have a test for this controller. If you're curios about the statement working, any javascript console here or on the lodash site will have lodash available for testing.
